#!/bin/bash

# Modified from:  http://en.gentoo-wiki.com/wiki/Portage_TMPDIR_on_tmpfs
# Store this file in /root and then do this:    ln -s /root/bemerge.sh /usr/local/sbin/bemerge &&  chmod u+x /usr/local/sbin/bemerge

. /etc/init.d/functions.sh


compile() {
	echo ""
	echo "  Welcome to *bemerge*"
	echo ""
	# Adding '--with-bdeps' because of http://bugs.gentoo.org/show_bug.cgi?id=357059
	# Make sure the next line matches up with the actual emerge command, that is, the line that starts with "/usr/bin/time"
	einfo "Running:  emerge --with-bdeps=y --keep-going=y ${*} ...\n"

	if [ -f /usr/bin/time ]
		then
			/usr/bin/time -f "\n\nEMERGE TOTALS...  Time used: %E  /  Avg CPU usage: %P  /  Max memory usage: %MK" emerge --with-bdeps=y --keep-going=y ${*}

	# The 'time' command used to also include "  /  Avg memory use: %KK" until I realized that the value was always shown as "0"
	# The reason for this, as confirmed from other websites, is listed in the time man page (http://linux.die.net/man/1/time):
	# "Not all resources are measured by all versions of Unix, so some of the values might be reported as zero. The present selection was mostly inspired by the data provided by 4.2 or 4.3BSD."
		else
			echo "/usr/bin/time not found, exiting." && exit
	fi
}


notice() {
                # String all these lines/commands together with "&&" so that if the user hits Ctrl-C anytime during the post-emerge process, then the whole post-emerge process dies.  But this method doesn't work on lines that have pipes  ("|") and so don't use it on those lines.
		echo "" && \
		einfo "Cleaning up non-local locale files..." && \
                if [ -f /usr/bin/localepurge ];
			then
				localepurge | grep freed
			else
				echo "/usr/bin/localepurge not found, exiting." && exit
		fi
		#
		einfo "Removing unneeded Portage install files..." && \
		# -d is not too destructive and without it you can have lots of unneccesary source code install files building up
		eclean-dist -d && \
		#
		einfo "Updating list of kernel modules provided by installed packages..." && \
		# From: http://www.gentoo.org/doc/en/kernel-upgrade.xml#doc_chap6
		# next line requires package "module-rebuild"
		[ -f /usr/sbin/module-rebuild ] && module-rebuild populate > /dev/null && \
		echo "" && \
		echo "" &&\
		einfo "You may also want to run:" && \
		einfo "" && \
		einfo "dispatch-conf | etc-update (update configuration files)" && \
		einfo "revdep-rebuild -- -av      (reverse dependency check)" && \
		einfo "module-rebuild rebuild     (rebuild kernel modules provided by ebuilds)" && \
		einfo "emerge --prune -av         (remove old versions from multiple-slots)" && \
		einfo "emerge --depclean -av      (remove packages not required anymore)" && \
		einfo "eselect                    (for certain updates requiring choices)" && \
		einfo "emaint -f all              (system health checks and fixes)" && \
		einfo "eix-test-obsolete detailed (for checking your /etc/portage files for unused entries)" && \
		einfo "eselect python update && python-updater" && \
		einfo "perl-cleaner --all         (for any perl installs)" && \
		einfo "binutils-config -l         (for binutils programs)" && \
		einfo "java-check-environment     (for any java installs)" && \
		einfo "mysql_upgrade -p           (for any mySQL upgrades -- then restart mysqld)" && \
		#
		# next line requires package "portage-utils"
		einfo "emerge -1av \$(qlist -IC x11-drivers/)   (rebuild drivers after xorg-sever upgrade)" && \
		#
		echo "" && \
		einfo "If you've upgraded GCC, then do  (from gentoo.org/doc/en/gcc-upgrading.xml):"
		echo "     gcc-config i686-pc-linux-gnu-X.X.X   (substitute new version for X.X.X)" && \
		echo "     env-update && source /etc/profile" && \
		echo "     emerge -1av libtool && emerge -eav system && emerge -eav world" && \
		echo "     (then remove the old version of GCC)" && \
		echo "" && \
		#
		# From: http://www.gentoo.org/news/en/gmn/20080930-newsletter.xml#doc_chap4_sect3
		# Adding "+c 0" to the "lsof" command in order to get the full filename.
		# Adding "| pr -a -t -2" in order to put it into two columns
		# must emerge lsof in order for this to work
		einfo "The following *in-use* files (if any) have been DELETED while emerge ran." && \
		echo  "   (you may want to restart related programs)..." && \
		if [ -f /usr/bin/lsof ];
			then
				lsof +c 0 | grep 'DEL.*lib' | cut -f 1 -d ' ' | sort -u | pr -a -t -2
		fi && \
		# requires the checkrestart package to be installed:
		echo ""
		einfo "If any of these can be restarted with an \"init script,\" they are listed below:" && \
		checkrestart| sed -n "/^These are the init scripts/,/These processes do not seem/p" | grep -v "These processes" | grep -v "These are the init"
		echo ""
	}


		
# Run emerge
compile $@

# Display info
notice
